### ISSUE TITLE
Melhorar legibilidade do Gráfico de Avaliação dos Processos

### ISSUE THREAD

**Issue by glandre** [MateusGabi/Trabalho-MPN-T2#5]
Olá pessoal,

Está muito difícil entender qual bolha representa qual processo no gráfico de bolhas, pois as cores estão muito parecidas. Seria possível deixar cores bem diferentes? Ou então colocar o nome de cada processo na bolha.

Att.,
Geraldo

**Comment by MateusGabi** [comment]
Ok, professor. Até terça estará pronto.

**Comment by JonathanJHK** [comment]
Tarefa já realizada!
