### ISSUE TITLE
HTML dos Processos na página do trabalho

### ISSUE THREAD

**Issue by glandre** [MateusGabi/Trabalho-MPN-T2#6]
Olá pessoal,

Percebi que a página do grupo de vocês já está em elaboração. Legal... Parabéns!
Apenas um detalhe, seria melhor **incorporar o HTML gerado pelo BizAgi no site**, mesmo que vocês apenas façam um link para uma nova página. Isso porque por meio dos HTML é possível navegar nos processos ler as descrições, etc.

Acredito que, para manter do jeito que vocês fizeram, dá pra colocar um `<iframe>`

Att.,
Geraldo

**Comment by MateusGabi** [comment]
Acabei de submeter!
